SPRITE_SCALING_PLAYER = 6
SPRITE_SCALING_enemy = 6
SPRITE_SCALING_LASER = 6

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Space Invaders"

PLAYER_BULLET_SPEED = 8
BULLET_SPEED = 5
ENEMY_SPEED = 1.5

MAX_PLAYER_BULLETS = 3

DEATH_PAUSE_TIME = 0.5

GAME_OVER_Y = 270

ENEMY_VERTICAL_MARGIN = 15
RIGHT_ENEMY_BORDER = SCREEN_WIDTH - ENEMY_VERTICAL_MARGIN
LEFT_ENEMY_BORDER = ENEMY_VERTICAL_MARGIN

ENEMY_MOVE_DOWN_AMOUNT = 40

PLAY_GAME = 0
GAME_OVER = 1
YOU_WIN = 2

PLAYER_COLOR = 62, 76, 41
ENEMY_EXPLOSION_COLOR = 185, 65, 65
